services:
  service-a:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    depends_on:
      - service-b

  service-b:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
